[WIP] Footer Block
EnsembleSystems/brother-usa-franklin-demo pull request #2
Opened 2024-03-01 20:54 UTC by maxwensemble

- Structure footer block
  - stayed connected
  - footer content
  - footer bottom
- Style footer block

2024-03-01 21:50 UTC, alexm-ens reviewed
One important thing to note, which I forgot to cover. When you create a pull request do not delete the template text, but update the "After: " with your new branch name.

For example your "block/footer" translate to "block-footer". A branch like "block/footer-settings-xyz" will translate to "block-footer-settings-xyz". I already updated your PR description for reference so you can take a look

2024-03-01 21:50 UTC, alexm-ens commented on blocks/footer-content/footer-content.css
> +    font-family: Helvetica Neue, Helvetica, Arial, sans-serif !important;
i feel like fonts Catamaran and Helveteica Neue are probably imported. So will need to import those fonts. We can chat about it in slack

2024-03-01 21:54 UTC, alexm-ens commented
Left and right margins are not the same as in the orginal website. Also the fonts, but i believe this will be fixed with the font imports. 
<img width="1724" alt="Screenshot 2024-03-01 at 1 50 32 PM" src="https://github.com/EnsembleSystems/brother-usa-franklin-demo/assets/144847859/94d24a44-07dd-4636-8073-b258799b3c0a">

Great job though! I think you made the right decision by not addign anything in .js files because all the content can be styled with css only. At least this is how it looks now. 
But yeah to reassure whenever we have blocks that do not need any extra js logic. We just a create an empty .js file. At least that what i was doing

2024-03-06 22:24 UTC, alexm-ens requested changes
I tried viewing the demo and it has some inconsistencies in the layout with the original website that i would want to address before we merge this

2024-03-06 22:24 UTC, alexm-ens commented on blocks/footer-content/footer-content.js
> +    bbbLogoLink.href = 'https://www.bbb.org/us/nj/bridgewater/profile/commercial-manufacturers/brother-international-corporation-0221-11003469#sealclick';
i suggest change link to "/" or if that does not work there is like a js snippet u can google to get the base URL. I highly suggest not to include external links at this stage as i dont know if we will need any. 

But kuddos to you this a very good production level code, if this was not a demo website this would be superb!

2024-03-06 22:24 UTC, alexm-ens commented on blocks/footer-global/footer-global.css
> +    background-color: var(--dark-blue);
I dont know if you have some extension in vscode that helps you quickly populate color values from CSS variables. In my vscode it was never aware what variables i have so to speed things up i just gave up on that.

So yeah if this practice takes more of your time instead of helping being efficient - drop it. For this project hardcoded values or not perfect not structured css is completely acceptable. 

But again if this was not a demo project this would be the golden standard ! 😄

2024-03-06 22:50 UTC, colewalker97 commented
hey @maxwensemble looking over the PR - looks good! nothing crazy jumped out at me. comparing this with the live site there are some subtle styling differences, mainly container width at various breakpoints. Not to sure how precise we want to be, ill defer to @alexm-ens.
only other thing I noticed is that the list item text content on the live site are wrapped in anchor tags, i'd suggest to add some styling properties for those as well. I added a hyperlink to one of the list items in your doc for reference

2024-03-06 23:05 UTC, alexm-ens commented
> hey @maxwensemble looking over the PR - looks good! nothing crazy jumped out at me. comparing this with the live site there are some subtle styling differences, mainly container width at various breakpoints. Not to sure how precise we want to be, ill defer to @alexm-ens. only other thing I noticed is that the list item text content on the live site are wrapped in anchor tags, i'd suggest to add some styling properties for those as well. I added a hyperlink to one of the list items in your footer doc for reference

yeah i agree about the layout it was my concern as well.  In this particular i case i say we need to fix it, as i think the change should be relatively easy, just some margins and max-width properties. There could be cases when we can deviate from the original design because the layout or design is too complex and not feasible to implement. 
But i dont think this is the case

2024-03-07 01:35 UTC, colewalker97 commented on blocks/footer-content/footer-content.css
> +    margin-right: 10%;
adding around 25% looks closer to the live site

2024-03-07 01:35 UTC, colewalker97 commented on blocks/footer-global/footer-global.css
try adding the following to help with the margin:
`.footer-global {
  display: flex;
  flex-direction: column;
  margin-left: 20%;
  margin-right: 20%;
}`

2024-03-07 01:36 UTC, colewalker97 commented on blocks/footer/footer.css
> +.footer {
try adding the following and let me know what you think
`.footer {
    position: absolute;
    margin-top: 110px;
    width: 100%;
    background: var(--light-blue);
}`

might look weird with whitespace below the footer, but once more content gets added to the index doc it'll dissipate. The `margin-top: 110px` should give you the same effect as your margin-top: 20% on the stay-connected wrapper property

2024-03-07 01:36 UTC, colewalker97 commented on blocks/stay-connected/stay-connected.css
> +    margin-top: 20%;
it looks like having this much margin will leave whitespace on the page once more content is added.
I would remove this and replace it with `max-width: 1140px` to give the container a closer width to the live site

2024-03-07 01:36 UTC, colewalker97 commented on blocks/stay-connected/stay-connected.css
> +.stay-connected-container {
try adding 20% margin-right & left here and see how it looks

2024-03-08 18:24 UTC, alexm-ens approved these changes
Good to merge

2024-03-08 18:24 UTC, alexm-ens commented on blocks/footer-content/footer-content.css
> +    margin-left: 15.25%;
dont need to change, but absolute values would probably be more preferrable for the demo. For other blocks specifically.

2024-03-08 18:25 UTC, merged